<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\store.jpg" />
		<Resource Include="Assets\logon.jpg" />
		<Resource Include="Assets\login.jpg" />
		<Resource Include="Assets\sop.png" />
		<Resource Include="Assets\back.jpg" />
		<Resource Include="Assets\pos.jpg" />
		<Resource Include="Assets\Logo.jpg" />
		<Resource Include="Assets\back.png" />
		<Resource Include="Assets\front.png" />
		<Resource Include="Assets\gateway.jpeg" />
	</ItemGroup>

</Project>