<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="ClosedXML" Version="0.105.1" />
		<PackageReference Include="QuestPDF" Version="2026.8.0" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\store.jpg" />
		<Resource Include="Assets\logon.jpg" />
		<Resource Include="Assets\login.jpg" />
		<Resource Include="Assets\sop.png" />
		<Resource Include="Assets\back.jpg" />
		<Resource Include="Assets\pos.jpg" />
		<Resource Include="Assets\Logo.jpg" />
		<Resource Include="Assets\back.png" />
		<Resource Include="Assets\front.png" />
		<Resource Include="Assets\gateway.jpeg" />
		<Resource Include="Assets\terminal.png" />
		<Resource Include="Assets\email.png" />
		<Resource Include="Assets\sms.png" />
		<Resource Include="Assets\estore.png" />
		<Resource Include="Assets\menulayout.png" />
		<Resource Include="Assets\tablesetting.png" />
		<Resource Include="Assets\wallet.png" />
		<Resource Include="Assets\mpesa.png" />
		<Resource Include="Assets\executequery.png" />
		<Resource Include="Assets\license.png" />
		<Resource Include="Assets\workperiod.png" />
		<Resource Include="Assets\mastersetting.png" />
		<Resource Include="Assets\profile.png" />
		<Resource Include="Assets\userroles.png" />
		<Resource Include="Assets\backup.png" />
		<Resource Include="Assets\categoryunit.png" />
		<Resource Include="Assets\items.png" />
		<Resource Include="Assets\purchaseentry.png" />
		<Resource Include="Assets\stocklevels.png" />
		<Resource Include="Assets\stockadjustment.png" />
		<Resource Include="Assets\warehouse.png" />
		<Resource Include="Assets\stocktransfer.png" />
		<Resource Include="Assets\supplier.png" />
		<Resource Include="Assets\hr.png" />
		<Resource Include="Assets\customers.png" />
		<Resource Include="Assets\supplierledger.png" />
		<Resource Include="Assets\expenses.png" />
		<Resource Include="Assets\expensemaster.png" />
		<Resource Include="Assets\finance.png" />
		<Resource Include="Assets\loyalty.png" />
		<Resource Include="Assets\vouchers.png" />
		<Resource Include="Assets\salesreports.png" />
		<Resource Include="Assets\stockreports.png" />
		<Resource Include="Assets\purchasereports.png" />
		<Resource Include="Assets\expensereports.png" />
		<Resource Include="Assets\accountingreports.png" />
		<Resource Include="Assets\logs.png" />
		<Resource Include="Assets\warehousecategory.png" />
		<Resource Include="Assets\itemcategory.png" />
		<Resource Include="Assets\expensecategory.png" />
		<Resource Include="Assets\unitcategory.png" />
		<Resource Include="Assets\exit_button.png" />
		<Resource Include="Assets\back-arrow.png" />
		<Resource Include="Assets\minimize.png" />
		<Resource Include="Assets\workp.png" />
		<Resource Include="Assets\pos.png" />
		<Resource Include="Assets\report.png" />
		<Resource Include="Assets\import.png" />
		<Resource Include="Assets\export.png" />
		<Resource Include="Assets\cusledger.png" />
		<Resource Include="Assets\employee.png" />
		<Resource Include="Assets\clockin.png" />
		<Resource Include="Assets\logout.png" />
	</ItemGroup>

</Project>